Repository palantir/conjure-java-runtime-api, pull requests merged in 2019-10, with the labels that each got.

#341 Create .changelog.yml
  .changelog.yml
Labels: merge when ready, no changelog

#348 fix #347: ServiceException retains causal `errorInstanceId`
  changelog/@unreleased/pr-348.v2.yml
  errors/src/main/java/com/palantir/conjure/java/api/errors/ServiceException.java
  errors/src/test/java/com/palantir/conjure/java/api/errors/ServiceExceptionTest.java
Labels: autorelease, merge when ready

#353 Fix #226: RemoteException messages are safe loggable
  changelog/@unreleased/pr-353.v2.yml
  errors/src/main/java/com/palantir/conjure/java/api/errors/RemoteException.java
  errors/src/test/java/com/palantir/conjure/java/api/errors/RemoteExceptionTest.java
Labels: merge when ready

#368 Redact password and token-related fields
  changelog/@unreleased/pr-368.v2.yml
  service-config/src/main/java/com/palantir/conjure/java/api/config/service/BasicCredentials.java
  service-config/src/main/java/com/palantir/conjure/java/api/config/service/PartialServiceConfiguration.java
  service-config/src/main/java/com/palantir/conjure/java/api/config/service/ServiceConfiguration.java
  service-config/src/main/java/com/palantir/conjure/java/api/config/service/ServicesConfigBlock.java
  ssl-config/src/main/java/com/palantir/conjure/java/api/config/ssl/SslConfiguration.java
Labels: autorelease, merge when ready

#369 Change ImmutablesStyle's retention policy
  errors/src/main/java/com/palantir/conjure/java/api/errors/ImmutablesStyle.java
  errors/src/main/java/com/palantir/conjure/java/api/errors/SerializableError.java
  service-config/src/main/java/com/palantir/conjure/java/api/config/service/ImmutablesStyle.java
  ssl-config/src/main/java/com/palantir/conjure/java/api/config/ssl/ImmutablesStyle.java
Labels: autorelease, no changelog

#356 Add 401 Unauthorized ErrorType
  changelog/@unreleased/pr-356.v2.yml
  errors/src/main/java/com/palantir/conjure/java/api/errors/ErrorType.java
  errors/src/test/java/com/palantir/conjure/java/api/errors/ErrorTypeTest.java
Labels: autorelease, merge when ready

#374 Make UnknownRemoteError safe-loggable
  changelog/@unreleased/pr-374.v2.yml
  errors/src/main/java/com/palantir/conjure/java/api/errors/UnknownRemoteException.java
  errors/src/test/java/com/palantir/conjure/java/api/errors/UnknownRemoteExceptionTest.java
Labels: autorelease, merge when ready
