Repository palantir/conjure-java-runtime-api, pull requests merged in 2023-11, with the labels that each got.

#1048 Add test coverage for current SerializableError.forException() behavior
  errors/src/test/java/com/palantir/conjure/java/api/errors/SerializableErrorTest.java
Labels: merge when ready, no changelog

#1047 Fix RawTypes warning in QosExceptionTest
  errors/src/test/java/com/palantir/conjure/java/api/errors/QosExceptionTest.java
Labels: merge when ready, no changelog

#1051 Test coverage for SerializableError.forException() with Optional values
  errors/src/test/java/com/palantir/conjure/java/api/errors/SerializableErrorTest.java
Labels: merge when ready, no changelog

#1056 Relax ErrorType namespace restrictions
  changelog/@unreleased/pr-1056.v2.yml
  errors/src/main/java/com/palantir/conjure/java/api/errors/ErrorType.java
  errors/src/test/java/com/palantir/conjure/java/api/errors/ErrorTypeTest.java
Labels: merge when ready, autorelease

#1058 Make ServiceException and RemoteException assertions better
  test-utils/src/main/java/com/palantir/conjure/java/api/testing/RemoteExceptionAssert.java
  test-utils/src/main/java/com/palantir/conjure/java/api/testing/ServiceExceptionAssert.java
  test-utils/src/test/java/com/palantir/conjure/java/api/testing/RemoteExceptionAssertTest.java
  test-utils/src/test/java/com/palantir/conjure/java/api/testing/ServiceExceptionAssertTest.java
Labels: merge when ready, no changelog, autorelease
