Repository palantir/conjure-java-runtime-api, pull requests merged in 2024-01, with the labels that each got.

#1074 Expose InstaceOfAssertFactory for exception asserts
  changelog/@unreleased/pr-1074.v2.yml
  test-utils/src/main/java/com/palantir/conjure/java/api/testing/Assertions.java
  test-utils/src/main/java/com/palantir/conjure/java/api/testing/QosExceptionAssert.java
  test-utils/src/main/java/com/palantir/conjure/java/api/testing/RemoteExceptionAssert.java
  test-utils/src/main/java/com/palantir/conjure/java/api/testing/ServiceExceptionAssert.java
Labels: merge when ready, autorelease

#1061 Eliminate some unused builders
  errors/src/main/java/com/palantir/conjure/java/api/errors/ErrorType.java
  service-config/src/main/java/com/palantir/conjure/java/api/config/service/BasicCredentials.java
Labels: merge when ready, no changelog, autorelease

#1057 Use SafeLoggable exceptions in more places
  errors/src/test/java/com/palantir/conjure/java/api/errors/QosExceptionTest.java
  errors/src/test/java/com/palantir/conjure/java/api/errors/SerializableErrorTest.java
  service-config/src/main/java/com/palantir/conjure/java/api/config/service/HostAndPort.java
  service-config/src/main/java/com/palantir/conjure/java/api/config/service/HumanReadableDuration.java
  service-config/src/main/java/com/palantir/conjure/java/api/config/service/ServiceConfigurationFactory.java
  service-config/src/test/java/com/palantir/conjure/java/api/config/service/ProxyConfigurationTests.java
  service-config/src/test/java/com/palantir/conjure/java/api/config/service/ServiceConfigurationFactoryTests.java
  ssl-config/build.gradle
  ssl-config/src/test/java/com/palantir/conjure/java/api/config/ssl/SslConfigurationTest.java
Labels: merge when ready, no changelog

#1085 Be more lenient when deserializing error parameters
  errors/src/main/java/com/palantir/conjure/java/api/errors/SerializableError.java
  errors/src/test/java/com/palantir/conjure/java/api/errors/SerializableErrorTest.java
Labels: merge when ready, no changelog, autorelease
